defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - plot_metrics
  - _self_

# Checkpoint and early stop based on metric logged by PTGLitModule.

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  # monitor: "val/loss"
  # mode: "min"
  monitor: "val/f1"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/f1"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
