version: "2.1"
title: "DessertQuesadilla"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 8
    label: "cutting board"
  - id: 9
    label: "butter knife"
  - id: 10
    label: "banana"
  - id: 11
    label: "banana (peeled)"
  - id: 12
    label: "sliced banana"
  - id: 13
    label: "cinnamon (open)"
  - id: 14
    label: "cinnamon (closed)"
  - id: 15
    label: "tortilla"
  - id: 16
    label: "tortilla bag"
  - id: 17
    label: "plate (empty)"
  # Labels unique to dessert quesadilla
  - id: 60
    label: "nutella jar lid"
  - id: 61
    label: "nutella jar (open)"
  - id: 62
    label: "nutella jar (closed)"
  - id: 63
    label: "butter knife + nutella"
  - id: 64
    label: "tortilla + nutella"
  - id: 65
    label: "tortilla + cinnamon"
  - id: 66
    label: "tortilla + nutella + sliced banana"
  - id: 67
    label: "tortilla + nutella + cinnamon"
  - id: 68
    label: "tortilla + nutella + sliced banana + cinnamon"
  - id: 69
    label: "folded tortilla (semi)"
  - id: 70
    label: "tortilla wedge"
  - id: 71
    label: "plate + tortilla wedge(s)"
