version: "2.2"
title: "Tea"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 5
    label: "water jug lid"
  - id: 6
    label: "water jug (open)"
  - id: 7
    label: "water jug (closed)"
  - id: 18
    label: "kettle lid"
  - id: 19
    label: "kettle (open)"
  - id: 20
    label: "kettle (closed)"
  - id: 21
    label: "spoon"
  - id: 22
    label: "jar of honey (open)"
  - id: 23
    label: "jar of honey (closed)"
  - id: 24
    label: "measuring cup"
  - id: 26
    label: "mug"
  - id: 27
    label: "kettle switch"
  - id: 28
    label: "thermometer (open)"
  - id: 29
    label: "thermometer (closed)"
  - id: 30
    label: "timer (on)"
  - id: 31
    label: "timer (off)"
  - id: 32
    label: "trash can"
  # Labels unique to tea
  - id: 115
    label: "tea bag (dry)"
  - id: 116
    label: "tea bag (wet)"
  - id: 117
    label: "mug + tea bag"
  - id: 118
    label: "mug + water"
  - id: 119
    label: "mug + tea bag + water"
  - id: 120
    label: "mug + tea"
