version: "2.0"
title: "Dessert Quesadilla"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 5
    label: "cutting board"
  - id: 6
    label: "butter knife"
  - id: 7
    label: "banana"
  - id: 8
    label: "sliced banana"
  - id: 9
    label: "cinnamon"
  - id: 10
    label: "tortilla"
  - id: 11
    label: "plate"
  # Labels unique to dessert quesadilla
  - id: 54
    label: "nutella"
  - id: 55
    label: "butter knife + nutella"
  - id: 56
    label: "tortilla + nutella"
  - id: 57
    label: "tortilla + cinnamon"
  - id: 58
    label: "tortilla + nutella + sliced banana"
  - id: 59
    label: "tortilla + nutella + cinnamon"
  - id: 60
    label: "tortilla + nutella + sliced banana + cinnamon"
  - id: 61
    label: "folded tortilla (semi)"
  - id: 62
    label: "tortilla wedge"
  - id: 63
    label: "plate + tortilla wedges"

