version: "2.0"
title: "Pinwheels"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 5
    label: "cutting board"
  - id: 6
    label: "butter knife"
  - id: 10
    label: "tortilla"
  - id: 11
    label: "plate"
  # Labels unique to pinwheels
  - id: 81
    label: "nut butter"
  - id: 82
    label: "jelly"
  - id: 83
    label: "toothpick"
  - id: 84
    label: "dental floss"
  - id: 85
    label: "butter knife + nut butter"
  - id: 86
    label: "butter knife + jelly"
  - id: 87
    label: "tortilla + nut butter"
  - id: 88
    label: "tortilla + jelly"
  - id: 89
    label: "tortilla + nut butter + jelly"
  - id: 90
    label: "tortilla (rolled)"
  - id: 91
    label: "pinwheel"
  - id: 92
    label: "plate + pinwheels"

