version: "3.0"
title: "Coffee+Tea"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "hand (left)"
  - id: 2
    label: "hand (right)"
  - id: 3
    label: "paper towel"
  - id: 4
    label: "paper towel sheet"
  - id: 5
    label: "water jug lid"
  - id: 6
    label: "water jug (open)"
  - id: 7
    label: "water jug (closed)"
  - id: 8
    label: "kettle lid"
  - id: 9
    label: "kettle (open)"
  - id: 10
    label: "kettle (closed)"
  - id: 11
    label: "measuring cup"
  - id: 12
    label: "container"
  - id: 13
    label: "mug"
  - id: 14
    label: "kettle switch"
  - id: 15
    label: "thermometer (open)"
  - id: 16
    label: "thermometer (closed)"
  - id: 17
    label: "timer (on)"
  - id: 18
    label: "timer (off)"
  - id: 19
    label: "trash can"
  - id: 20
    label: "coffee + mug"
  - id: 21
    label: "coffee bag"
  - id: 22
    label: "coffee beans + container"
  - id: 23
    label: "coffee beans + container + scale"
  - id: 24
    label: "coffee grounds + paper filter (quarter - open) + dripper"
  - id: 25
    label: "coffee grounds + paper filter (quarter - open) + dripper + mug"
  - id: 26
    label: "container + scale"
  - id: 27
    label: "dripper"
  - id: 28
    label: "dripper + mug"
  - id: 29
    label: "grinder lid"
  - id: 30
    label: "grinder (open)"
  - id: 31
    label: "grinder (closed)"
  - id: 32
    label: "paper filter"
  - id: 33
    label: "paper filter (semi)"
  - id: 34
    label: "paper filter (quarter)"
  - id: 35
    label: "used paper filter (quarter) + dripper"
  - id: 36
    label: "paper filter (quarter) + dripper"
  - id: 37
    label: "paper filter (quarter) + dripper + mug"
  - id: 38
    label: "paper filter (quarter - open) + dripper"
  - id: 39
    label: "paper filter (quarter - open) + dripper + mug"
  - id: 40
    label: "paper filter bag"
  - id: 41
    label: "stack of paper filters"
  - id: 42
    label: "scale (on)"
  - id: 43
    label: "scale (off)"
  - id: 44
    label: "used paper filter"
  - id: 45
    label: "used paper filter (quarter - open) + dripper"
  - id: 46
    label: "used paper filter (quarter - open) + dripper + mug"
  - id: 47
    label: "used paper filter (quarter) + dripper + mug"
  - id: 48
    label: "spoon"
  - id: 49
    label: "jar of honey (open)"
  - id: 50
    label: "jar of honey (closed)"
  - id: 51
    label: "tea bag (dry)"
  - id: 52
    label: "tea bag (wet)"
  - id: 53
    label: "mug + tea bag"
  - id: 54
    label: "mug + water"
  - id: 55
    label: "mug + tea bag + water"
  - id: 56
    label: "mug + tea"
